### PR TITLE
Add --tag-scope to support separate versioning for branches

### LINKED ISSUE #188: CLI flag to bump version based from working dir instead latest VCS tag
The title says it all.

I read the reasoning in the README under ['Bump it up'](https://github.com/mbarkhau/bumpver#bump-it-up) for making the decision to take as the current version the most recent one from the VCS tags, globally across all branches.

But there are use-cases, especially with release branches, where the current version should be taken from the current working directory. This is already shown in bumpver output, however I was expecting a CLI flag to switch this behavior if needed, but could not find it. More frustrating even is, that setting the version manually won't work either, as bumpver still compares this against the most current version it found.

In case you are interested, the use case I am facing currently:
Stable/main branch on version 1.0.1
Release branch with additional features on version 1.1.0rc2
In the mean time I want to push some minor fixes to the stable branch, e.g. incrementing it to 1.0.2.
To me it seems this kind of branch structure might be quite common so I was wondering, why bumpver is not supporting this kind of behavior.

### PR DESCRIPTION
**Pull request by malnvenshorn**
Closes #188 

Implemented as suggested in the related issue. New `--tag-scope` parameter for the CLI and `tag_scope` option for the config file.

| `--tag-scope=` | `current_version =` |
| --- | --- |
| `default` | `max(config.current_version, max(global_vcs_tags))` 
| `global` | `max(global_vcs_tags)` |
| `branch` | `max(branch_vcs_tags)` |

- `--tag-scope=branch` is only supported for Git, an error is raised if used with Mercurial
-  When using `--tag-scope=branch`, an error is raised if the new version conflicts with a tag on another branch
- Independent of the `--tag-scope` parameter `bumpver` defaults to `config.current_version` if no tags are found
- Also check if `new_version` is unique when using `--set-version`

#### Checklist
- [x] Add tests
- [x] Run: make fmt lint mypy test test_compat
- [x] Update documentation

### CODE REVIEW

**Comment by malnvenshorn** [comment]
I guess this can be reviewed now. Feel free to give some feedback on this @mbarkhau @demmerichs

**Comment by mbarkhau** [comment]
> `ImportError: No module named enum`

Can you avoid usage of the `enum` module?

**Comment by malnvenshorn** [comment]
Just added the `enum` backport for old Python versions. Tests should work now.

**Comment by mbarkhau** [comment]
LGTM. Great work!

Any objections after my updates?

**Comment by malnvenshorn** [comment]
No, looks good. Thanks for adding support for Mercurial.

**Pull request merged**
