### PR TITLE
Optional GITHASH directive for version_pattern

### PR DESCRIPTION
**Pull request by mpasternak**
Optionally add GIT hash to your version number.

I use bumpver and I'm pretty happy about it. 

From time to time I'd like to create an ad-hoc version of my packages for testing purposes and be able to name it so it contains a git hash, like this (excerpt from my actual [Makefile](https://github.com/iplweb/bpp/blob/dev/Makefile#L137)):

```makefile

set-version-from-vcs:
	$(eval CUR_VERSION_VCS=$(shell git describe | sed s/\-/\./ | sed s/\-/\+/))
	bumpver update --no-commit --set-version=$(CUR_VERSION_VCS)
```

This pull request allows us to use [GITHASH] directive in version_pattern. 

When a version is given with the format as above (for example it is ``202201.40.8+deadbeef``), it gets parsed properly with setuptools (``8`` gets parsed to ``micro`` and ``deadbeef`` to local parts respectively) and ``python setup.py build`` will not complain. 

Of course I don't plan to distribute those packages externally. 

Of course I don't plan to use "bumpver update" with such version numbers, it would make no sense to commit or tag using those versions; this is why I recommend using ``--no-tag-commit`` and ``--no-commit`` in the docs. 

When I came to this problem I analyzed using ``grep`` and ``sed`` for this, but on the other hand, as I already have locations of my versions well described in ``setup.cfg``... why bother? 

Please let me know what you think. 

Thanks, 
-- 
m

PS: I do realize, that the source code of ``bumpver`` looks pretty much formatted. I refrained from re-formatting it, as it would make this diff much more noisy than it should be. Thank you for understanding.

### CODE REVIEW

**Comment by mbarkhau** [comment]
Related #176

**Comment by mbarkhau** [comment]
I think we can merge the feature in principle, but I wonder if it's such a corner case, that we best not even document it. Can you think of some other way to satisfy your requirements that would also allow for a full fledged part, without the caveats you're documenting?

**Comment by mbarkhau** [comment]
I'll think about it. I'll have more time later this week.

**Comment by mpasternak** [comment]
This is a small change in code and docs but a non-trivial change in the workflow, raising more questions than answers. 

I suggest using this git-hash including version number "only once", to generate a package from git repo. In this terms this is more like a tag - not a release tag, but a git tag. Almost the same thing, only I don't have to think how to name it, it is already named, a autogenerated hash. 

What if "bumpver update" sees such version number? It should drop the git tag completely? Should it raise an exception? I have no idea. Perhaps if we can decide what the behavior should be in such cases, the rest will somehow solve itself.

**Comment by mbarkhau** [comment]
Obsolete by #179

**Pull request closed without merging**
